In [1]:
import pandas as pd

In [127]:
df = pd.read_csv('2017_dem.csv')
df

,GEO.id,GEO.id2,GEO.display-label,POPGROUP.id,POPGROUP.display-label,EST_VC03,MOE_VC03,EST_VC04,MOE_VC04,EST_VC05,...,EST_VC457,MOE_VC457,EST_VC458,MOE_VC458,EST_VC462,MOE_VC462,EST_VC463,MOE_VC463,EST_VC464,MOE_VC464
0,Id,Id2,Geography,Id,Population Group,Estimate; TOTAL NUMBER OF RACES REPORTED - Tot...,Margin of Error; TOTAL NUMBER OF RACES REPORTE...,Estimate; TOTAL NUMBER OF RACES REPORTED - Tot...,Margin of Error; TOTAL NUMBER OF RACES REPORTE...,Estimate; TOTAL NUMBER OF RACES REPORTED - Tot...,...,Estimate; GROSS RENT - Occupied units paying rent,Margin of Error; GROSS RENT - Occupied units p...,Estimate; GROSS RENT - Occupied units paying r...,Margin of Error; GROSS RENT - Occupied units p...,Estimate; COMPUTERS AND INTERNET USE - Total h...,Margin of Error; COMPUTERS AND INTERNET USE - ...,Estimate; COMPUTERS AND INTERNET USE - Total h...,Margin of Error; COMPUTERS AND INTERNET USE - ...,Estimate; COMPUTERS AND INTERNET USE - Total h...,Margin of Error; COMPUTERS AND INTERNET USE - ...
1,0400000US01,01,Alabama,001,Total population,4874747,*****,98.1,0.1,1.8,...,525186,9896,750,11,1841665,12421,86.1,0.4,78.1,0.5
2,0400000US02,02,Alaska,001,Total population,739795,*****,91.4,0.7,7.9,...,84396,3696,1201,41,250741,3074,94.2,0.6,86.1,1.2
3,0400000US04,04,Arizona,001,Total population,7016270,*****,96.2,0.2,3.5,...,859557,13010,1020,9,2552972,11005,92.2,0.3,85.7,0.3
4,0400000US05,05,Arkansas,001,Total population,3004279,*****,97.2,0.2,2.7,...,365461,8588,711,10,1153082,8560,86.3,0.5,73.0,0.7
5,0400000US06,06,California,001,Total population,39536653,*****,95.1,0.1,4.4,...,5697421,26766,1447,5,13005097,17539,93.5,0.1,87.7,0.1
6,0400000US08,08,Colorado,001,Total population,5607154,*****,96.5,0.2,3.1,...,717989,11693,1240,13,2139207,8774,94.2,0.2,88.2,0.3
7,0400000US09,09,Connecticut,001,Total population,3588184,*****,96.7,0.2,2.9,...,439295,7765,1125,13,1356762,6513,90.9,0.4,85.5,0.5
8,0400000US10,10,Delaware,001,Total population,961939,*****,97.0,0.4,2.8,...,99986,4411,1086,22,357937,4266,92.9,0.7,86.2,1.0
9,0400000US11,11,District of Columbia,001,Total population,693972,*****,97.0,0.5,2.7,...,158550,4053,1499,35,281475,3302,91.9,0.8,82.7,1.1
10,0400000US12,12,Florida,001,Total population,20984400,*****,97.4,0.1,2.4,...,2565527,21240,1128,5,7689964,22835,91.9,0.2,83.2,0.2
11,0400000US13,13,Georgia,001,Total population,10429379,*****,97.3,0.1,2.5,...,1321593,18186,958,8,3745074,16431,90.9,0.2,82.7,0.4
12,0400000US15,15,Hawaii,001,Total population,1427538,*****,76.7,0.9,14.4,...,177512,4269,1573,36,458078,4221,91.3,0.8,84.5,0.8
13,0400000US16,16,Idaho,001,Total population,1716943,*****,96.9,0.4,2.8,...,177724,5943,822,16,625135,5980,91.3,0.6,82.5,0.9
14,0400000US17,17,Illinois,001,Total population,12802023,*****,97.4,0.1,2.5,...,1558423,14714,974,6,4808672,14430,90.3,0.2,83.6,0.2
15,0400000US18,18,Indiana,001,Total population,6666818,*****,97.3,0.1,2.5,...,747371,11576,793,6,2557299,10669,88.8,0.3,81.2,0.4
16,0400000US19,19,Iowa,001,Total population,3145711,*****,97.8,0.2,2.1,...,335444,7691,760,9,1257505,6773,89.5,0.4,81.8,0.5
17,0400000US20,20,Kansas,001,Total population,2913123,*****,96.5,0.2,3.3,...,365853,6439,815,11,1128983,6821,90.7,0.4,83.0,0.5
18,0400000US21,21,Kentucky,001,Total population,4454189,*****,97.7,0.1,2.1,...,524986,9042,724,8,1725034,10346,86.3,0.4,78.9,0.5
19,0400000US22,22,Louisiana,001,Total population,4684333,*****,98.2,0.2,1.7,...,539054,11985,836,9,1737123,11255,86.0,0.5,75.6,0.6
20,0400000US23,23,Maine,001,Total population,1335907,*****,97.7,0.2,2.2,...,133662,4721,806,22,540959,6050,89.7,0.6,82.0,0.7
21,0400000US24,24,Maryland,001,Total population,6052177,*****,96.6,0.2,3.0,...,709705,11380,1337,12,2207343,8135,93.0,0.3,87.7,0.4
22,0400000US25,25,Massachusetts,001,Total population,6859819,*****,96.9,0.2,2.9,...,951688,10737,1208,12,2604954,9148,91.2,0.3,86.8,0.3
23,0400000US26,26,Michigan,001,Total population,9962311,*****,97.0,0.1,2.8,...,1070220,12285,835,6,3930017,12926,90.0,0.2,82.8,0.2
24,0400000US27,27,Minnesota,001,Total population,5576606,*****,97.2,0.2,2.6,...,590552,8548,939,10,2162211,7968,92.1,0.2,85.9,0.3
25,0400000US28,28,Mississippi,001,Total population,2984100,*****,98.6,0.2,1.3,...,300261,9495,742,11,1091980,9693,84.6,0.5,73.4,0.6
26,0400000US29,29,Missouri,001,Total population,6113532,*****,97.4,0.1,2.4,...,739845,12023,800,9,2385135,13054,89.7,0.3,81.3,0.4
27,0400000US30,30,Montana,001,Total population,1050493,*****,96.8,0.3,3.1,...,119850,4105,759,20,423091,4068,88.7,0.7,81.3,0.9
28,0400000US31,31,Nebraska,001,Total population,1920076,*****,97.3,0.2,2.5,...,239436,6475,801,13,754490,4583,90.8,0.4,84.4,0.5
29,0400000US32,32,Nevada,001,Total population,2998039,*****,95.4,0.3,4.1,...,462895,8980,1051,13,1094613,6821,93.3,0.4,83.4,0.5
30,0400000US33,33,New Hampshire,001,Total population,1342795,*****,97.9,0.2,2.0,...,154201,4734,1072,21,528700,4349,93.7,0.5,88.4,0.6
31,0400000US34,34,New Jersey,001,Total population,9005644,*****,97.5,0.1,2.4,...,1129441,12076,1284,11,3218798,8951,92.6,0.2,86.8,0.3
32,0400000US35,35,New Mexico,001,Total population,2088070,*****,96.7,0.3,3.2,...,224577,6783,813,18,767705,6614,86.6,0.7,76.4,0.7
33,0400000US36,36,New York,001,Total population,19849399,*****,97.0,0.1,2.8,...,3255748,20629,1226,8,7304332,18884,90.1,0.2,83.4,0.2
34,0400000US37,37,North Carolina,001,Total population,10273419,*****,97.4,0.1,2.4,...,1280412,15400,861,6,3955069,14774,89.4,0.3,81.6,0.4
35,0400000US38,38,North Dakota,001,Total population,755393,*****,98.0,0.3,1.8,...,107867,3634,785,19,316306,3300,90.5,0.7,81.3,1.1
36,0400000US39,39,Ohio,001,Total population,11658609,*****,97.1,0.1,2.7,...,1516601,15083,772,5,4667192,13650,89.6,0.2,83.2,0.2
37,0400000US40,40,Oklahoma,001,Total population,3930864,*****,92.3,0.2,7.2,...,463286,7203,780,7,1470364,5913,89.2,0.3,79.7,0.4
38,0400000US41,41,Oregon,001,Total population,4142776,*****,95.2,0.2,4.4,...,573421,9839,1079,12,1603635,8695,93.2,0.4,86.8,0.5
39,0400000US42,42,Pennsylvania,001,Total population,12805537,*****,97.5,0.1,2.3,...,1491279,16792,893,5,5008751,12653,88.0,0.2,81.5,0.3
40,0400000US44,44,Rhode Island,001,Total population,1059639,*****,96.7,0.5,3.1,...,154825,4583,941,19,408748,4427,89.7,0.8,85.5,0.9
41,0400000US45,45,South Carolina,001,Total population,5024369,*****,97.9,0.2,2.0,...,545954,11858,848,9,1905100,10277,88.8,0.3,79.2,0.4
42,0400000US46,46,South Dakota,001,Total population,869666,*****,97.4,0.3,2.4,...,104764,3806,722,18,344260,3147,88.4,0.7,80.6,1.0
43,0400000US47,47,Tennessee,001,Total population,6715984,*****,97.9,0.1,2.0,...,828612,13672,833,9,2588655,10916,87.4,0.3,79.4,0.5
44,0400000US48,48,Texas,001,Total population,28304596,*****,97.4,0.1,2.5,...,3486567,28563,987,5,9623874,22217,91.8,0.1,83.3,0.2
45,0400000US49,49,Utah,001,Total population,3101833,*****,97.0,0.2,2.7,...,281943,6252,986,15,975448,5045,95.5,0.3,87.8,0.5
46,0400000US50,50,Vermont,001,Total population,623657,*****,97.9,0.3,2.0,...,73452,3449,950,28,256629,3631,89.5,0.9,81.4,1.1
47,0400000US51,51,Virginia,001,Total population,8470020,*****,96.1,0.2,3.5,...,990189,11278,1179,11,3120880,13665,91.8,0.2,84.8,0.3
48,0400000US53,53,Washington,001,Total population,7405743,*****,94.1,0.2,5.3,...,1013454,14151,1216,13,2840377,11168,94.2,0.3,89.1,0.3
49,0400000US54,54,West Virginia,001,Total population,1815857,*****,98.3,0.2,1.5,...,166391,6120,690,15,715308,7000,84.6,0.7,76.0,0.8
50,0400000US55,55,Wisconsin,001,Total population,5795483,*****,97.5,0.1,2.3,...,751576,9645,819,6,2350293,7563,89.5,0.3,83.3,0.3
51,0400000US56,56,Wyoming,001,Total population,579315,*****,97.2,0.4,2.5,...,59964,3676,832,26,225796,3968,91.7,1.0,83.7,1.1

In [128]:
df.columns = df.iloc[0]

In [129]:
df = df[1:]

In [130]:
df

,Id,Id2,Geography,Id,Population Group,Estimate; TOTAL NUMBER OF RACES REPORTED - Total population,Margin of Error; TOTAL NUMBER OF RACES REPORTED - Total population,Estimate; TOTAL NUMBER OF RACES REPORTED - Total population - One race,Margin of Error; TOTAL NUMBER OF RACES REPORTED - Total population - One race,Estimate; TOTAL NUMBER OF RACES REPORTED - Total population - Two races,...,Estimate; GROSS RENT - Occupied units paying rent,Margin of Error; GROSS RENT - Occupied units paying rent,Estimate; GROSS RENT - Occupied units paying rent - Median gross rent (dollars),Margin of Error; GROSS RENT - Occupied units paying rent - Median gross rent (dollars),Estimate; COMPUTERS AND INTERNET USE - Total households,Margin of Error; COMPUTERS AND INTERNET USE - Total households,Estimate; COMPUTERS AND INTERNET USE - Total households - With a computer,Margin of Error; COMPUTERS AND INTERNET USE - Total households - With a computer,Estimate; COMPUTERS AND INTERNET USE - Total households - With a broadband Internet subscription,Margin of Error; COMPUTERS AND INTERNET USE - Total households - With a broadband Internet subscription
1,0400000US01,01,Alabama,001,Total population,4874747,*****,98.1,0.1,1.8,...,525186,9896,750,11,1841665,12421,86.1,0.4,78.1,0.5
2,0400000US02,02,Alaska,001,Total population,739795,*****,91.4,0.7,7.9,...,84396,3696,1201,41,250741,3074,94.2,0.6,86.1,1.2
3,0400000US04,04,Arizona,001,Total population,7016270,*****,96.2,0.2,3.5,...,859557,13010,1020,9,2552972,11005,92.2,0.3,85.7,0.3
4,0400000US05,05,Arkansas,001,Total population,3004279,*****,97.2,0.2,2.7,...,365461,8588,711,10,1153082,8560,86.3,0.5,73.0,0.7
5,0400000US06,06,California,001,Total population,39536653,*****,95.1,0.1,4.4,...,5697421,26766,1447,5,13005097,17539,93.5,0.1,87.7,0.1
6,0400000US08,08,Colorado,001,Total population,5607154,*****,96.5,0.2,3.1,...,717989,11693,1240,13,2139207,8774,94.2,0.2,88.2,0.3
7,0400000US09,09,Connecticut,001,Total population,3588184,*****,96.7,0.2,2.9,...,439295,7765,1125,13,1356762,6513,90.9,0.4,85.5,0.5
8,0400000US10,10,Delaware,001,Total population,961939,*****,97.0,0.4,2.8,...,99986,4411,1086,22,357937,4266,92.9,0.7,86.2,1.0
9,0400000US11,11,District of Columbia,001,Total population,693972,*****,97.0,0.5,2.7,...,158550,4053,1499,35,281475,3302,91.9,0.8,82.7,1.1
10,0400000US12,12,Florida,001,Total population,20984400,*****,97.4,0.1,2.4,...,2565527,21240,1128,5,7689964,22835,91.9,0.2,83.2,0.2
11,0400000US13,13,Georgia,001,Total population,10429379,*****,97.3,0.1,2.5,...,1321593,18186,958,8,3745074,16431,90.9,0.2,82.7,0.4
12,0400000US15,15,Hawaii,001,Total population,1427538,*****,76.7,0.9,14.4,...,177512,4269,1573,36,458078,4221,91.3,0.8,84.5,0.8
13,0400000US16,16,Idaho,001,Total population,1716943,*****,96.9,0.4,2.8,...,177724,5943,822,16,625135,5980,91.3,0.6,82.5,0.9
14,0400000US17,17,Illinois,001,Total population,12802023,*****,97.4,0.1,2.5,...,1558423,14714,974,6,4808672,14430,90.3,0.2,83.6,0.2
15,0400000US18,18,Indiana,001,Total population,6666818,*****,97.3,0.1,2.5,...,747371,11576,793,6,2557299,10669,88.8,0.3,81.2,0.4
16,0400000US19,19,Iowa,001,Total population,3145711,*****,97.8,0.2,2.1,...,335444,7691,760,9,1257505,6773,89.5,0.4,81.8,0.5
17,0400000US20,20,Kansas,001,Total population,2913123,*****,96.5,0.2,3.3,...,365853,6439,815,11,1128983,6821,90.7,0.4,83.0,0.5
18,0400000US21,21,Kentucky,001,Total population,4454189,*****,97.7,0.1,2.1,...,524986,9042,724,8,1725034,10346,86.3,0.4,78.9,0.5
19,0400000US22,22,Louisiana,001,Total population,4684333,*****,98.2,0.2,1.7,...,539054,11985,836,9,1737123,11255,86.0,0.5,75.6,0.6
20,0400000US23,23,Maine,001,Total population,1335907,*****,97.7,0.2,2.2,...,133662,4721,806,22,540959,6050,89.7,0.6,82.0,0.7
21,0400000US24,24,Maryland,001,Total population,6052177,*****,96.6,0.2,3.0,...,709705,11380,1337,12,2207343,8135,93.0,0.3,87.7,0.4
22,0400000US25,25,Massachusetts,001,Total population,6859819,*****,96.9,0.2,2.9,...,951688,10737,1208,12,2604954,9148,91.2,0.3,86.8,0.3
23,0400000US26,26,Michigan,001,Total population,9962311,*****,97.0,0.1,2.8,...,1070220,12285,835,6,3930017,12926,90.0,0.2,82.8,0.2
24,0400000US27,27,Minnesota,001,Total population,5576606,*****,97.2,0.2,2.6,...,590552,8548,939,10,2162211,7968,92.1,0.2,85.9,0.3
25,0400000US28,28,Mississippi,001,Total population,2984100,*****,98.6,0.2,1.3,...,300261,9495,742,11,1091980,9693,84.6,0.5,73.4,0.6
26,0400000US29,29,Missouri,001,Total population,6113532,*****,97.4,0.1,2.4,...,739845,12023,800,9,2385135,13054,89.7,0.3,81.3,0.4
27,0400000US30,30,Montana,001,Total population,1050493,*****,96.8,0.3,3.1,...,119850,4105,759,20,423091,4068,88.7,0.7,81.3,0.9
28,0400000US31,31,Nebraska,001,Total population,1920076,*****,97.3,0.2,2.5,...,239436,6475,801,13,754490,4583,90.8,0.4,84.4,0.5
29,0400000US32,32,Nevada,001,Total population,2998039,*****,95.4,0.3,4.1,...,462895,8980,1051,13,1094613,6821,93.3,0.4,83.4,0.5
30,0400000US33,33,New Hampshire,001,Total population,1342795,*****,97.9,0.2,2.0,...,154201,4734,1072,21,528700,4349,93.7,0.5,88.4,0.6
31,0400000US34,34,New Jersey,001,Total population,9005644,*****,97.5,0.1,2.4,...,1129441,12076,1284,11,3218798,8951,92.6,0.2,86.8,0.3
32,0400000US35,35,New Mexico,001,Total population,2088070,*****,96.7,0.3,3.2,...,224577,6783,813,18,767705,6614,86.6,0.7,76.4,0.7
33,0400000US36,36,New York,001,Total population,19849399,*****,97.0,0.1,2.8,...,3255748,20629,1226,8,7304332,18884,90.1,0.2,83.4,0.2
34,0400000US37,37,North Carolina,001,Total population,10273419,*****,97.4,0.1,2.4,...,1280412,15400,861,6,3955069,14774,89.4,0.3,81.6,0.4
35,0400000US38,38,North Dakota,001,Total population,755393,*****,98.0,0.3,1.8,...,107867,3634,785,19,316306,3300,90.5,0.7,81.3,1.1
36,0400000US39,39,Ohio,001,Total population,11658609,*****,97.1,0.1,2.7,...,1516601,15083,772,5,4667192,13650,89.6,0.2,83.2,0.2
37,0400000US40,40,Oklahoma,001,Total population,3930864,*****,92.3,0.2,7.2,...,463286,7203,780,7,1470364,5913,89.2,0.3,79.7,0.4
38,0400000US41,41,Oregon,001,Total population,4142776,*****,95.2,0.2,4.4,...,573421,9839,1079,12,1603635,8695,93.2,0.4,86.8,0.5
39,0400000US42,42,Pennsylvania,001,Total population,12805537,*****,97.5,0.1,2.3,...,1491279,16792,893,5,5008751,12653,88.0,0.2,81.5,0.3
40,0400000US44,44,Rhode Island,001,Total population,1059639,*****,96.7,0.5,3.1,...,154825,4583,941,19,408748,4427,89.7,0.8,85.5,0.9
41,0400000US45,45,South Carolina,001,Total population,5024369,*****,97.9,0.2,2.0,...,545954,11858,848,9,1905100,10277,88.8,0.3,79.2,0.4
42,0400000US46,46,South Dakota,001,Total population,869666,*****,97.4,0.3,2.4,...,104764,3806,722,18,344260,3147,88.4,0.7,80.6,1.0
43,0400000US47,47,Tennessee,001,Total population,6715984,*****,97.9,0.1,2.0,...,828612,13672,833,9,2588655,10916,87.4,0.3,79.4,0.5
44,0400000US48,48,Texas,001,Total population,28304596,*****,97.4,0.1,2.5,...,3486567,28563,987,5,9623874,22217,91.8,0.1,83.3,0.2
45,0400000US49,49,Utah,001,Total population,3101833,*****,97.0,0.2,2.7,...,281943,6252,986,15,975448,5045,95.5,0.3,87.8,0.5
46,0400000US50,50,Vermont,001,Total population,623657,*****,97.9,0.3,2.0,...,73452,3449,950,28,256629,3631,89.5,0.9,81.4,1.1
47,0400000US51,51,Virginia,001,Total population,8470020,*****,96.1,0.2,3.5,...,990189,11278,1179,11,3120880,13665,91.8,0.2,84.8,0.3
48,0400000US53,53,Washington,001,Total population,7405743,*****,94.1,0.2,5.3,...,1013454,14151,1216,13,2840377,11168,94.2,0.3,89.1,0.3
49,0400000US54,54,West Virginia,001,Total population,1815857,*****,98.3,0.2,1.5,...,166391,6120,690,15,715308,7000,84.6,0.7,76.0,0.8
50,0400000US55,55,Wisconsin,001,Total population,5795483,*****,97.5,0.1,2.3,...,751576,9645,819,6,2350293,7563,89.5,0.3,83.3,0.3
51,0400000US56,56,Wyoming,001,Total population,579315,*****,97.2,0.4,2.5,...,59964,3676,832,26,225796,3968,91.7,1.0,83.7,1.1

In [131]:
df.drop(['Id', 'Id2', 'Id', 'Population Group'], axis=1, inplace=True)

In [132]:
df = df.T

In [118]:
monster_data.index

RangeIndex(start=1, stop=52, step=1)

In [133]:
df_cols = [col for col in df.index if 'Median family income' in col]
print(df_cols)

['Estimate; INCOME IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars)', 'Margin of Error; INCOME IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars)', 'Estimate; INCOME IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars) - Married-couple family', 'Margin of Error; INCOME IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars) - Married-couple family']

In [139]:
df = df.T

In [135]:
df_colz = ['Estimate; INCOME IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars)']

In [149]:
df = df.T

In [152]:
income_2017 = df[['Geography', 'Estimate; INCOME IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars)']]

In [154]:
income_2017 = income_2017.rename(columns={"Estimate; INCOME IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars)": "Median Income"})

In [161]:
income_2017 = income_2017.rename(columns={"Geography": "State"})

In [162]:
income_2017['Year'] = 2017
income_2017

0                  State Median Income  Year
1                Alabama         61512  2017
2                 Alaska         86831  2017
3                Arizona         67886  2017
4               Arkansas         57421  2017
5             California         82009  2017
6               Colorado         84918  2017
7            Connecticut         93870  2017
8               Delaware         77082  2017
9   District of Columbia        106528  2017
10               Florida         64003  2017
11               Georgia         67983  2017
12                Hawaii         91460  2017
13                 Idaho         64178  2017
14              Illinois         79168  2017
15               Indiana         68085  2017
16                  Iowa         75076  2017
17                Kansas         72057  2017
18              Kentucky         61593  2017
19             Louisiana         60510  2017
20                 Maine         72177  2017
21              Maryland         98393  2017
22         Massachusetts         98758  2017
23              Michigan         69664  2017
24             Minnesota         86416  2017
25           Mississippi         55937  2017
26              Missouri         67317  2017
27               Montana         68994  2017
28              Nebraska         75112  2017
29                Nevada         68276  2017
30         New Hampshire         91029  2017
31            New Jersey         97300  2017
32            New Mexico         58308  2017
33              New York         80114  2017
34        North Carolina         65964  2017
35          North Dakota         81869  2017
36                  Ohio         69632  2017
37              Oklahoma         61471  2017
38                Oregon         73202  2017
39          Pennsylvania         75949  2017
40          Rhode Island         84557  2017
41        South Carolina         62432  2017
42          South Dakota         73236  2017
43             Tennessee         62926  2017
44                 Texas         70136  2017
45                  Utah         77940  2017
46               Vermont         74426  2017
47              Virginia         86279  2017
48            Washington         84594  2017
49         West Virginia         56086  2017
50             Wisconsin         75413  2017
51               Wyoming         74868  2017

In [76]:
state = monster_data['Geography']

In [77]:
df['State'] = state

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [121]:
income_2016 = df[['State', 'Estimate; INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars)']]

KeyError: "['State'] not in index"

In [124]:
income_2016 = income_2017.rename(columns={"Estimate; INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars)": "Median Income"})

In [158]:
income_2016['Year'] = 2016

In [163]:
df_16_17 = income_2016.merge(income_2017, how='left', on=['State'])

In [165]:
df_16_17.to_csv('Median Income 2016-2017')

In [166]:
voter_percent = pd.read_csv('hate_crimes.csv')

In [168]:
voter_percent = voter_percent[['state', 'share_voters_voted_trump']]

In [175]:
voter_percent.to_csv('Voter Percentage')

In [173]:
voter_percent = voter_percent.rename(columns={'state': 'State'})

                   State  share_voters_voted_trump
0                Alabama                      0.63
1                 Alaska                      0.53
2                Arizona                      0.50
3               Arkansas                      0.60
4             California                      0.33
5               Colorado                      0.44
6            Connecticut                      0.41
7               Delaware                      0.42
8   District of Columbia                      0.04
9                Florida                      0.49
10               Georgia                      0.51
11                Hawaii                      0.30
12                 Idaho                      0.59
13              Illinois                      0.39
14               Indiana                      0.57
15                  Iowa                      0.52
16                Kansas                      0.57
17              Kentucky                      0.63
18             Louisiana                      0.58
19                 Maine                      0.45
20              Maryland                      0.35
21         Massachusetts                      0.34
22              Michigan                      0.48
23             Minnesota                      0.45
24           Mississippi                      0.58
25              Missouri                      0.57
26               Montana                      0.57
27              Nebraska                      0.60
28                Nevada                      0.46
29         New Hampshire                      0.47
30            New Jersey                      0.42
31            New Mexico                      0.40
32              New York                      0.37
33        North Carolina                      0.51
34          North Dakota                      0.64
35                  Ohio                      0.52
36              Oklahoma                      0.65
37                Oregon                      0.41
38          Pennsylvania                      0.49
39          Rhode Island                      0.40
40        South Carolina                      0.55
41          South Dakota                      0.62
42             Tennessee                      0.61
43                 Texas                      0.53
44                  Utah                      0.47
45               Vermont                      0.33
46              Virginia                      0.45
47            Washington                      0.38
48         West Virginia                      0.69
49             Wisconsin                      0.48
50               Wyoming                      0.70

In [172]:
hate_17 = pd.read_csv('hate_crime_2017.csv')
vote_haters = voter_percent.merge(hate_17, how='left', on=['State'])

KeyError: 'State'

In [174]:
hate_17

,Table 12,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"Agency Hate Crime Reporting by State, 2017",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Participating state,Number of\nparticipating\nagencies,Population\ncovered,Agencies\nsubmitting\nincident\nreports,Total\nnumber of\nincidents\nreported,NaN,NaN,NaN
2,Total,"16,149","306,435,676","2,040","7,175",NaN,NaN,NaN
3,Alabama,334,"2,918,324",3,9,NaN,NaN,NaN
4,Alaska,32,"736,205",3,4,NaN,NaN,NaN
5,Arizona,87,"6,755,795",20,264,NaN,NaN,NaN
6,Arkansas,292,"2,836,240",4,7,NaN,NaN,NaN
7,California,730,"39,529,144",232,"1,094",NaN,NaN,NaN
8,Colorado,221,"5,575,629",43,106,NaN,NaN,NaN
9,Connecticut,107,"3,588,184",44,111,NaN,NaN,NaN
10,Delaware,63,"961,939",11,29,NaN,NaN,NaN
11,District of Columbia,2,"693,972",2,193,NaN,NaN,NaN
12,Florida,654,"20,515,334",67,145,NaN,NaN,NaN
13,Georgia,509,"8,948,013",8,27,NaN,NaN,NaN
14,Idaho,106,"1,699,259",21,53,NaN,NaN,NaN
15,Illinois,741,"12,270,234",32,82,NaN,NaN,NaN
16,Indiana,162,"2,287,298",21,55,NaN,NaN,NaN
17,Iowa,240,"3,104,739",8,11,NaN,NaN,NaN
18,Kansas,364,"2,620,785",38,75,NaN,NaN,NaN
19,Kentucky,409,"4,444,239",132,378,NaN,NaN,NaN
20,Louisiana,145,"3,764,930",15,26,NaN,NaN,
21,Maine,132,"1,335,907",10,32,NaN,NaN,NaN
22,Maryland,154,"6,052,177",18,48,NaN,NaN,NaN
23,Massachusetts,360,"6,703,220",102,427,NaN,NaN,NaN
24,Michigan,624,"9,928,921",177,456,NaN,NaN,NaN
25,Minnesota,353,"5,508,515",42,146,NaN,NaN,NaN
26,Mississippi,28,"682,046",1,1,NaN,NaN,NaN
27,Missouri,610,"6,109,596",32,105,NaN,NaN,NaN
28,Montana,110,"1,050,005",11,15,NaN,NaN,NaN
29,Nebraska,238,"1,865,845",9,45,NaN,NaN,NaN
30,Nevada,51,"2,998,039",3,5,NaN,NaN,NaN
31,New Hampshire,177,"1,295,556",13,13,NaN,NaN,NaN
32,New Jersey,518,"9,005,644",155,495,NaN,NaN,NaN
33,New Mexico,17,"561,375",1,7,NaN,NaN,NaN
34,New York,567,"19,685,625",74,552,NaN,NaN,NaN
35,North Carolina,527,"10,271,767",44,166,NaN,NaN,NaN
36,North Dakota,110,"754,604",8,15,NaN,NaN,NaN
37,Ohio,572,"9,703,884",137,380,NaN,NaN,NaN
38,Oklahoma,412,"3,916,111",27,37,NaN,NaN,NaN
39,Oregon,214,"3,902,529",29,146,NaN,NaN,NaN
40,Pennsylvania,"1,488","12,730,580",23,78,NaN,NaN,NaN
41,Rhode Island,49,"1,059,639",4,11,NaN,NaN,NaN
42,South Carolina,438,"4,996,532",46,87,NaN,NaN,NaN
43,South Dakota,116,"799,083",10,17,NaN,NaN,NaN
44,Tennessee,466,"6,715,984",57,136,NaN,NaN,NaN
45,Texas,"1,009","28,096,894",75,190,NaN,NaN,NaN
46,Utah,126,"3,056,326",27,78,NaN,NaN,NaN
47,Vermont,90,"623,657",17,34,NaN,NaN,NaN
48,Virginia,413,"8,467,744",65,193,NaN,NaN,NaN
49,Washington,243,"7,396,166",72,510,NaN,NaN,NaN
50,West Virginia,245,"1,591,058",20,31,NaN,NaN,NaN
51,Wisconsin,437,"5,767,235",24,46,NaN,NaN,NaN
52,Wyoming,57,"553,149",3,4,NaN,NaN,NaN